

# This file was *autogenerated* from the file Sage/GBasis.sage
from sage.all_cmdline import *   # import sage library

_sage_const_0 = Integer(0); _sage_const_1 = Integer(1)
import argparse
import ast
import re
import io
import contextlib
import json

from sage.all import PolynomialRing, QQ, lcm
from fractions import Fraction
from itertools import combinations, product

def extract_vars(set_str):

    tokens = re.findall(r'[a-zA-Z_][a-zA-Z0-9_]*', set_str)

    seen = set()
    ordered_vars = []
    for var in tokens:
        if var not in seen:
            seen.add(var)
            ordered_vars.append(var)

    return ordered_vars



def create_polynomial_ring(vars_list, order='lex', base_ring=QQ):

    if order not in ['lex', 'degrevlex', 'deglex']:
        raise ValueError(f"Unsupported order: {order}")

    R = PolynomialRing(base_ring, vars_list, order=order)
    return R

def convert_polylist_to_json(quotients, vars_list):
    json_quotients = []
    num_vars = len(vars_list)
    
    var_to_index = {var: i for i, var in enumerate(vars_list)}

    for q_poly in quotients:
        terms_list = []
        
        # parse 0-polynomial
        if q_poly.is_zero():
            terms_list.append({
                "c": [int(_sage_const_0 ), int(_sage_const_1 )], 
                "e": [] 
            })
        else:
            for exp_tuple, coeff in q_poly.dict().items():
                # process coefficient
                if coeff.parent() is QQ:
                    # process rational number
                    coeff_num = int(coeff.numerator())
                    coeff_den = int(coeff.denominator())
                elif coeff.is_integer():
                    # process int number
                    coeff_num = int(coeff)
                    coeff_den = _sage_const_1 
                else:
                    coeff_num = int(coeff)
                    coeff_den = _sage_const_1 

                
                # process exponent
                exponent_pairs = []
                for i, power in enumerate(exp_tuple):
                    if power != _sage_const_0 :
                        exponent_pairs.append([i, int(power)])

                terms_list.append({
                    "c": [coeff_num, coeff_den],
                    "e": exponent_pairs
                })

        json_quotients.append(terms_list)

    return json_quotients


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description = "Compute Groebner Basis and output as JSON.")

    parser.add_argument('-s', '--set', type = str, required=True, help="Input polynomial set, e.g., 'x^2-y, y^2-x'")
    parser.add_argument('-o', '--order', type = str, default='lex', choices=['lex', 'degrevlex', 'deglex'], help="Monomial order for the Groebner basis.")

    args = parser.parse_args()

    try:
        vars_list = extract_vars(args.set)

        if not vars_list:
            raise ValueError("We can not find any variable in the input polynomial.")

        ring = create_polynomial_ring(vars_list, order=args.order)

        with contextlib.redirect_stdout(io.StringIO()):
            ring.inject_variables()
        
        cleaned_str = args.set.strip().strip('[]')

        if not cleaned_str:
            set_list = []
        else:
            set_list_str = [s.strip() for s in cleaned_str.split(',') if s.strip()]
            poly_list = [ring(s) for s in set_list_str]
        
        if not poly_list:
             raise ValueError("The input polynomial set is empty after parsing.")
        

        ideal = ring.ideal(poly_list)
        
        groebner_basis = ideal.groebner_basis()
        print(f"Groebner Basis {groebner_basis}")


        json_output = convert_polylist_to_json(groebner_basis, vars_list)

        print(json.dumps(json_output))
        
    except Exception as e:
        print(f"\n[!!! Error !!!] : {e}")
        import traceback
        traceback.print_exc()

