

# This file was *autogenerated* from the file /Users/tsuki/Desktop/GroebnerTac/Sage/Ideal.sage
from sage.all_cmdline import *   # import sage library

_sage_const_0 = Integer(0); _sage_const_1 = Integer(1)# This is a file used for tactic `ideal`
# Input : the generator list of ideal `I` and `J`
# Output : The coeffs of the linear combination of `f` in `I` with respect to `J` and the linear combination of `g` in `J` with respect to `I`
import re
import argparse
import io
import contextlib
import json

from sage.all import PolynomialRing, QQ

def extract_vars(str1, str2):
    combined_str = str1 + " " + str2

    tokens = re.findall(r'[a-zA-Z_][a-zA-Z0-9_]*', combined_str)

    seen = set()
    ordered_vars = []
    for var in tokens:
        if var not in seen:
            seen.add(var)
            ordered_vars.append(var)
    def natural_keys(text):
       return [int(c) if c.isdigit() else c for c in re.split(r'(\d+)', text)]

    ordered_vars.sort(key=natural_keys)

    return ordered_vars

def create_polynomial_ring(vars_list, order='lex', base_ring=QQ):

    if order not in ['lex', 'degrevlex', 'deglex']:
        raise ValueError(f"Unsupported order: {order}")

    R = PolynomialRing(base_ring, vars_list, order=order)
    return R

def parse_polynomials(ring, generator_list):
    """
    Convert list of str to list of polynomial
    """
    parsed_polys = []
    for poly_str in generator_list:
        try:
            poly = ring(poly_str)
            parsed_polys.append(poly)
        except Exception as e:
            raise ValueError(f"Could not parse polynomial string '{poly_str}' in ring {ring.name()}: {e}")
    return parsed_polys

def find_linear_representation(poly_list_to_represent, ideal_basis, ideal_name, basis_name):
    R = ideal_basis[_sage_const_0 ].parent()
    results = []

    I_basis = R.ideal(ideal_basis)
    
    B = I_basis.groebner_basis()
    
    for poly in poly_list_to_represent:
        try:
            is_contained = poly.reduce(B).is_zero()

            coeffs = poly.lift(I_basis)
            results.append(coeffs)

        except Exception as e:

            print(f"\n[Error In Find Representation] : {e}")
            import traceback
            traceback.print_exc()

    return results

# def convert_polys_to_json(polys, vars_list):
#     json_polys = []
#     num_vars = len(vars_list)
    
#     var_to_index = {var: i for i, var in enumerate(vars_list)}

#     for q_poly in polys:
#         if isinstance(q_poly, str):
#             q_poly = ring(q_poly)
#         else:
#             q_poly = q_poly
#         terms_list = []
        
#         # parse 0-polynomial
#         if q_poly.is_zero():
#             terms_list.append({
#                 "c": [int(0), int(1)], 
#                 "e": [] 
#             })
#         else:
#             for exp_tuple, coeff in q_poly.dict().items():
#                 # process coefficient
#                 if coeff.parent() is QQ:
#                     # process rational number
#                     coeff_num = int(coeff.numerator())
#                     coeff_den = int(coeff.denominator())
#                 elif coeff.is_integer():
#                     # process int number
#                     coeff_num = int(coeff)
#                     coeff_den = 1
#                 else:
#                     coeff_num = int(coeff)
#                     coeff_den = 1

                
#                 # process exponent
#                 exponent_pairs = []
#                 for i, power in enumerate(exp_tuple):
#                     if power != 0:
#                         exponent_pairs.append([int(i-1), int(power)])

#                 terms_list.append({
#                     "c": [coeff_num, coeff_den],
#                     "e": exponent_pairs
#                 })

#         json_polys.append(terms_list)

#     return json_polys

def convert_polys_to_json(polys, vars_list):
    json_polys = []
    
    if polys and hasattr(polys[_sage_const_0 ], 'parent'):
        ring_gens = polys[_sage_const_0 ].parent().gens()
    else:
        ring_gens = []

    for q_poly in polys:
        
        terms_list = []
        
        if q_poly.is_zero():
            terms_list.append({
                "c": [int(_sage_const_0 ), int(_sage_const_1 )], 
                "e": [] 
            })
        else:
            for exp_tuple, coeff in q_poly.dict().items():
                
                if hasattr(coeff, 'numerator') and hasattr(coeff, 'denominator'):
                    coeff_num = int(coeff.numerator())
                    coeff_den = int(coeff.denominator())
                else:
                    coeff_num = int(coeff)
                    coeff_den = _sage_const_1 

                exponent_pairs = []
                for i, power in enumerate(exp_tuple):
                    if power != _sage_const_0 :
                        
                        current_var_name = str(ring_gens[i])
                        
                        match = re.search(r'_(\d+)$', current_var_name)
                        if match:
                            real_index = int(match.group(_sage_const_1 ))
                        else:
                            try:
                                real_index = vars_list.index(current_var_name)
                            except:
                                real_index = i

                        exponent_pairs.append([real_index, int(power)])
  
                exponent_pairs.sort(key=lambda x: x[_sage_const_0 ])

                terms_list.append({
                    "c": [coeff_num, coeff_den],
                    "e": exponent_pairs
                })

        json_polys.append(terms_list)

    return json_polys
   

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description = "ideal")

    parser.add_argument('-I', '--generator1', type = str, required=True)

    parser.add_argument('-J', '--generator2', type = str, required=True)

    args = parser.parse_args()

    # print(f"I Generator {args.I}")
    # print(f"J Generator {args.J}")

    try:
        # Extract variables
        vars_list = extract_vars(args.generator1, args.generator2)

        if not vars_list:
            raise ValueError("We can not find any variable in the input polynomial")

        # make the polynomial ring
        ring = create_polynomial_ring(vars_list)

        # make polynomial ring with variables
        with contextlib.redirect_stdout(io.StringIO()):
            # make polynomial ring with variables
            ring.inject_variables()

        # convert str to polynomial list
        cleaned_str_1 = args.generator1.strip().strip('[]')
        cleaned_str_2 = args.generator2.strip().strip('[]')

        if not cleaned_str_1:
            generator_1 = []
        else:
            generator_1 = [s.strip() for s in cleaned_str_1.split(',') if s.strip()]

        if not cleaned_str_2:
            generator_2 = []
        else:
            generator_2 = [s.strip() for s in cleaned_str_2.split(',') if s.strip()]

        G1 = parse_polynomials(ring, generator_1)
        G2 = parse_polynomials(ring, generator_2)
        
        if not G1 or not G2:
            print("\n[!!! Warning !!!] One or both generator lists are empty. Cannot proceed with representation calculation.")
        else:
            I = ring.ideal(G1)
            J = ring.ideal(G2)

        results_G1_in_J = find_linear_representation(G1, G2, "G1", "G2")
        results_G2_in_I = find_linear_representation(G2, G1, "G2", "G1")

        # print(f"results_G1_in_J : {results_G1_in_J}\n\n")
        # print(f"results_G2_in_I : {results_G2_in_I}\n\n")
        
        json_result_1 = []
        for coeffs_list in results_G1_in_J:
            json_result_1.append(convert_polys_to_json(coeffs_list, vars_list))
        
        json_result_2 = []
        for coeffs_list in results_G2_in_I:
            # print(f"[results_G2_in_I]: {coeffs_list}\n")
            # print(f"[results_G2_in_I]: {convert_polys_to_json(coeffs_list, vars_list)}\n\n")
            json_result_2.append(convert_polys_to_json(coeffs_list, vars_list))

        result = []
        # print(f"json_result_1 : {json_result_1}\n\n")
        # print(f"json_result_2 : {json_result_2}\n\n")
        result.append(json_result_1)
        result.append(json_result_2)

        print(json.dumps(result))

        # result = []

        # json_G1_in_J = convert_polys_to_json(results_G1_in_J, vars_list)
        # result.append(json_G1_in_J)

        # json_G2_in_I = convert_polys_to_json(results_G2_in_I, vars_list)
        # result.append(json_G2_in_I)
        # print(json.dumps(result))

        
    except Exception as e:
        print(f"\n[!!! Ideal Error !!!] : {e}")
        import traceback
        traceback.print_exc()

