

# This file was *autogenerated* from the file Sage/lift.sage
from sage.all_cmdline import *   # import sage library

_sage_const_2 = Integer(2); _sage_const_1 = Integer(1); _sage_const_4 = Integer(4)
import argparse
import re
import sys
import json
from sage.all import PolynomialRing, QQ

def main():
    R = PolynomialRing(QQ, names='x,y,z,t', order='lex')
    x, y, z, t = R.gens()

    poly = y - x**_sage_const_2  + _sage_const_1 
    poly_1 = R(_sage_const_1 )  
    
    B_list = [t*poly - _sage_const_1 , x*y**_sage_const_2  + _sage_const_2 *y**_sage_const_2 , x**_sage_const_4  - _sage_const_2 *x**_sage_const_2  + _sage_const_1 ]
    
    I = R.ideal(B_list)

    is_contained = (_sage_const_1  in I)

    print(f"1 是否属于理想 B: {is_contained}")

    if is_contained:
        try:

            coeffs = I.lift(poly_1)
            
        except AttributeError:

            I_sing = I._singular_()
            poly_sing = poly_1._singular_()

            lift_result_matrix = I_sing.lift(poly_sing)
            coeffs = [R(lift_result_matrix[i+_sage_const_1 , _sage_const_1 ]) for i in range(len(B_list))]

        for i, coeff in enumerate(coeffs):
            print(f"  B[{i}] corff: {coeff}")
        check_sum = sum(coeffs[i] * B_list[i] for i in range(len(B_list)))


    else:
        print("1 is not in idea")

if __name__ == "__main__":
    main()

